config: src/exp_configs/tpch/catune-gpt-5.2-seed100-catune.yml
folder: catune-gpt-5.2-seed100-pure_202602152137
process: optimization
db: postgres
database: workload
test: tpch
timeout: 180
seed: 20
result_path: ./experiments_results/tpch/catune-gpt-5.2-seed100-pure_202602152137
knobs: catune/target_knobs.txt
suggest_range_path: None
suggest_range_target_path: None
suggest_range_mode: default
suggest_values_path: None
special_skill_path: None
special_skill_base_path: None
special_skill_mode: default
model: gpt-5.2
restart_cmd: echo 251314 | sudo -S docker restart benchbase
recover_script: ./scripts/recover_docker_postgres.sh
rules: true
sampling_strategy: uniform
user: postgres
password: postgres
knowledge_folder: experiments_results/tpch/catune-gpt-5.2-seed100-pure_202602152137/knowledge_collection
